# Generated by Django 4.0.1 on 2022-02-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='post',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.post'),
            preserve_default=False,
        ),
    ]
