# Generated by Django 4.0.1 on 2022-02-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_image_remove_post_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='posts.commentpost'),
        ),
    ]
